
server:
  port: 8500

# local

spring:
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:postgresql://localhost:5432/commerce
    password: celal371
    username: postgres
    driver-class-name: org.postgresql.Driver
    platform: postgresql
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    properties:
      jakarta:
        persistence:
          validation:
            mode: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  main:
    allow-circular-references: true
  sql:
    init:
      mode: NEVER
  data:
    web:
      pageable:
        default-page-size: 5
        max-page-size: 100
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB




eczaneLink: http://222.111.7.222:1212/
upload-path: image
upload-barcode-path:  barcode
upload-docs-path:  docs

app.jwt.expiration-in-ms: 86400000
app.jwt.token.prefix: Bearer
app.jwt.header.string: Authorization
app.jwt.secret: RandomSecretKey
