
INSERT INTO public.country (country_id, "name", "english_name") VALUES(1, 'TURKIYE', 'TURKEY');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(2, 'ABHAZYA', 'ABKHAZIA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(3, 'AFGANISTAN', 'AFGHANISTAN');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(4, 'ALMANYA', 'GERMANY');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(5, 'AMERIKA BIRLESIK DEVLETLERI', 'UNITED STATES');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(6, 'ANDORRA', 'ANDORRA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(7, 'ANGOLA', 'ANGOLA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(8, 'ANTIGUA VE BARBUDA','ANTIGUA AND BARBUDA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(9, 'ARJANTIN', 'ARGENTINA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(10, 'ARNAVUTLUK', 'ALBANIA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(11, 'AVUSTRALYA', 'AUSTRALIA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(12, 'AVUSTURYA', 'AUSTRIA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(13, 'AZERBAYCAN', 'AZERBAIJAN');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(14, 'BAHAMALAR', 'BAHAMAS');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(15, 'BAHREYN', 'BAHRAIN');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(16, 'BANGLADEŞ', 'BANGLADESH');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(17, 'BARBADOS', 'BARBADOS');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(18, 'BATI SAHRA', 'WESTERN SAHARA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(19, 'BELCIKA','BELGIUM');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(20, 'BELIZE', 'BELIZE');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(21, 'BENIN', 'BENIN');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(22, 'BEYAZ RUSYA', 'REPUBLIC OF BELARUS');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(23, 'BUTAN KRALLIGI', 'KINGDOM OF BHUTAN');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(24, 'BIRLESIK ARAP EMIRLIKLERI', 'UNITED ARAB EMIRATES');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(25, 'BOLIVYA', 'BOLIVIA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(26, 'BOSNA HERSEK', 'BOSNIA AND HERZEGOVINA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(27, 'BOTSVANA', 'BOTSWANA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(28, 'BREZILYA', 'BRAZIL');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(29, 'BRUNEI', 'BRUNEI');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(30, 'BULGARISTAN', 'BULGARIA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(31, 'BURKINA FASO', 'BURKINA FASO');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(32, 'BURUNDI', 'BURUNDI');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(33, 'CEZAYIR', 'ALGERIA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(34, 'CIBUTI', 'DJIBOUTI');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(35, 'CAD', 'CHAD');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(36, 'CEK CUMHURIYETI', 'CZECH REPUBLIC');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(37, 'CIN HALK CUMHURIYETI', 'PEOPLES REPUBLIC OF CHINA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(38, 'DAGLIK KARABAG CUMHURIYETI', 'NAGORNO-KARABAKH REPUBLIC ');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(39, 'DANIMARKA', 'DENMARK');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(40, 'DOGU TIMOR', 'EAST TIMOR');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(41, 'DOMINIK CUMHURIYETI', 'DOMINICAN REPUBLIC');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(42, 'DOMINIKA', 'DOMINICA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(43, 'EKVADOR', 'ECUADOR');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(44, 'EKVATOR GINESI', 'EQUATORIAL GUINEA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(45, 'EL SALVADOR', 'EL SALVADOR');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(46, 'ENDONEZYA', 'INDONESIA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(47, 'ERITRE', 'ERITREA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(48, 'ERMENISTAN', 'ARMENIA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(49, 'ESTONYA', 'ESTONIA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(50, 'ETIYOPYA', 'ETHIOPIA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(51, 'FAS', 'MOROCCO');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(52, 'FIJI', 'FIJI');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(53, 'FILDISI SAHILLERI', 'IVORY COAST');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(54, 'FILIPINLER', 'PHILIPPINES');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(55, 'FILISTIN', 'PALESTINE');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(56, 'FINLANDIYA', 'FINLAND');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(57, 'FRANSA', 'FRANCE');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(58, 'GABON','GABON');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(59, 'GAMBIYA', 'GAMBIA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(60, 'GANA', 'GHANA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(61, 'GINE', 'GUINEA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(62, 'GINE BISSAU', 'GINE BISSAU');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(63, 'GRENADA', 'GRENADA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(64, 'GUYANA', 'GUYANA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(65, 'GUATEMALA', 'GUATEMALA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(66, 'GUNEY AFRIKA CUMHURIYETI', 'SOUTH AFRICA REPUBLIC');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(67, 'GUNEY KORE', 'SOUTH KOREA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(68, 'GUNEY OSETYA', 'SOUTH OSSETIA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(69, 'GUNEY SUDAN', 'SOUTH SUDAN');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(70, 'GURCISTAN', 'GEORGIA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(71, 'HAITI', 'HAITI');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(72, 'HIRVATISTAN', 'CROATIA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(73, 'HINDISTAN', 'INDIA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(74, 'HOLLANDA', 'NETHERLANDS');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(75, 'HONDURAS', 'HONDURAS');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(76, 'IRAK', 'IRAQ');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(77, 'INGILTERE', 'ENGLAND');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(78, 'IRAN', 'PERSIA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(79, 'IRLANDA', 'IRELAND');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(80, 'ISPANYA', 'SPAIN');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(81, 'ISRAIL', 'ISRAEL');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(82, 'ISVEC', 'SWEDEN');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(83, 'ISVICRE', 'SWITZERLAND');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(84, 'ITALYA', 'ITALY');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(85, 'IZLANDA', 'ICELAND');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(86, 'JAMAIKA', 'JAMAICA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(87, 'JAPONYA', 'JAPAN');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(88, 'KAMBOCYA', 'CAMBODIA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(89, 'KAMERUN', 'CAMEROON');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(90, 'KANADA', 'CANADA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(91, 'KARADAG', 'MONTENEGRO');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(92, 'KAZAKISTAN', 'KAZAKHISTAN');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(93, 'KENYA', 'KENYA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(94, 'KIRGIZISTAN', 'KYRGYZSTAN');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(95, 'KIBRIS CUMHURIYETI', 'CYPRUS');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(96, 'KIRIBATI', 'KIRIBATI');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(97, 'KOLOMBIYA', 'COLOMBIA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(98, 'KOMORLAR', 'COMOROS');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(99, 'KONGO', 'CONGO');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(100, 'KONGO DEMOKRATIK CUMHURIYETI', 'DEMOCRATIC REBUPLIC OF THE CONGO ');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(101, 'KOSOVA', 'KOSOVA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(102, 'KOSTA RIKA', 'COSTA RICA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(103, 'KUVEYT', 'KUWAIT');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(104, 'KUZEY KIBRIS TURK CUMHURIYETI', 'TURKISH REPUBLIC OF NORTHEN CYPRUS ');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(105, 'KUZEY KORE', 'NORTH KOREA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(106, 'KUBA', 'CUBA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(107, 'LAOS', 'LAOS');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(108, 'LESOTHO', 'LESOTHO');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(109, 'LETONYA', 'LATVIA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(110, 'LIBERYA', 'LIBERIA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(111, 'LIBYA', 'LIBYA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(112, 'LIECHTENSTEIN', 'LIECHTENSTEIN');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(113, 'LITVANYA', 'LITHUANIA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(114, 'LUBNAN', 'LEBANON');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(115, 'LUKSEMBURG', 'LUXEMBOURG');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(116, 'MISIR', 'EGYPT');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(117, 'MACARISTAN', 'HUNGARY');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(118, 'MADAGASKAR', 'MADAGASCAR');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(119, 'MAKEDONYA CUMHURIYETI', 'REBUPLIC OF MACEDONIA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(120, 'MALAVI', 'MALAWI');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(121, 'MALDIVLER', 'MALDIVES');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(122, 'MALEZYA', 'MALAYSIA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(123, 'MALI', 'MALI');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(124, 'MALTA', 'MALTA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(125, 'MARSHALL ADALARI', 'MARSHALL ISLANDS');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(126, 'MOLDOVA', 'MOLDOVA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(127, 'MOZAMBIK', 'MOZAMBIQUE');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(128, 'NAMIBYA', 'NAMIBIA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(129, 'NIKARAGUA', 'NICARAGUA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(130, 'NIJER', 'NIGER');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(131, 'NIJERYA', 'NIGERIA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(132, 'NORVEC', 'NORWAY');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(133, 'ORTA AFRIKA CUMHURIYETI', 'CENTRAL AFRICAN REPUBLIC');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(134, 'OZBEKISTAN', 'UZBEKISTAN');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(135, 'PAKISTAN', 'PAKISTAN');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(136, 'PALAU', 'PALAU');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(137, 'PANAMA', 'PANAMA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(138, 'PAPUA', 'PAPUA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(139, 'PARAGUAY', 'PARAGUAY');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(140, 'PERU', 'PERU');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(141, 'POLONYA', 'POLAND');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(142, 'PORTEKIZ', 'PORTUGAL');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(143, 'PORTO RIKO', 'PORTO RICO');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(144, 'ROMANYA', 'ROMANIA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(145, 'RUANDA', 'RWANDA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(146, 'RUSYA FEDERASYONU', 'RUSSIAN FEDERATION');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(147, 'SAINT KITTS', 'SAINT KITTS');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(148, 'SAINT LUCIA', 'SAINT LUCIA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(149, 'SAINT VINCENT ve GRENADINLER', 'SAINT VINCENT AND THE GRENADINES ');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(150, 'SAMOA', 'SAMOA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(151, 'SAN MARINO', 'SAN MARINO');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(152, 'SAO TOME ve PRINCIPE', 'SAO TOME AND PRINCIPE');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(153, 'SEALAND', 'SEALAND');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(154, 'SENEGAL', 'SENEGAL');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(155, 'SEYSELLER', 'SEYCHELLES');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(156, 'SIRBISTAN', 'SERBIA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(157, 'SIERRA LEONE', 'SIERRA LEONE');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(158, 'SINGAPUR', 'SINGAPORE');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(159, 'SLOVAKYA', 'SLOVAKIA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(160, 'SLOVENYA', 'SLOVENIA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(161, 'SOLOMON ADALARI', 'SOLOMON ISLANDS');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(162, 'SOMALI', 'SOMALIA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(163, 'SOMALILAND', 'SOMALILAND');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(164, 'SRI LANKA', 'SRI LANKA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(165, 'SUDAN', 'SUDAN');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(166, 'SURINAM', 'SURINAME');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(167, 'SURIYE', 'SYRIA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(168, 'SUUDI ARABISTAN', 'SAUDI ARABIA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(169, 'SVAZILAND', 'SWAZILAND');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(170, 'SILI', 'CHILE');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(171, 'TACIKISTAN', 'TAJIKISTAN');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(172, 'TANZANYA', 'TANZANIA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(173, 'TAYLAND', 'THAILAND');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(174, 'TAYVAN', 'TAIWAN');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(175, 'TOGO', 'TOGO');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(176, 'TONGA', 'TONGA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(177, 'TRANSDINYESTER', 'TRANSNISTRIA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(178, 'TRINAD ve TOBAGO', 'TRINAD AND TOBAGO ');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(179, 'TUNUS', 'TUNISIA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(180, 'TUVALU', 'TUVALU');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(181, 'TURKMENISTAN', 'TURKMENISTAN');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(182, 'UGANDA', 'UGANDA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(183, 'UKRAYNA', 'UKRAINE');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(184, 'UMMAN', 'OMAN');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(185, 'URUGAY', 'URUGUAY');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(186, 'URDUN', 'JORDAN');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(187, 'VANUATU', 'VANUATU');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(188, 'VATIKAN', 'VATICAN');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(189, 'VENEZUELA', 'VENEZUELAN');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(190, 'VIETNAM', 'VIETNAMASE');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(191, 'YEMEN', 'YEMEN');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(192, 'YENI ZELANDA', 'NEW ZELAND');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(193, 'YESIL BURUN', 'CAPE VERDE');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(194, 'YUNANISTAN', 'GREECE');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(195, 'ZAMBIYAV', 'ZAMBIA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(196, 'ZIMBABVE', 'ZIMBABWE');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(197, 'MEKSIKA', 'MEXICAN');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(198, 'NAURU', 'NAURU');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(199, 'NEPAL', 'NEPAL');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(200, 'MONAKO','MONACO');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(201, 'MORITANYA', 'MAURITANIA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(202, 'MORITIUS', 'MAURITIUS');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(203, 'KATAR', 'QATAR');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(204, 'BURMA (MYANMAR)', 'MYANMAR');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(205, 'HONG KONG', 'HONG KONG');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(206, 'MAKAO', 'MACAU');




INSERT INTO public.company
(company_id, address, city, company_fax, company_mobile_phone, company_name, company_phone, created_date, currency_type, email_address, status, tax_no, countryid, userid)
VALUES(nextval('sq_company'), '', 'Ankara', '', '', 'STOK', '', '01/01/2021', 'TL', '', 1, '', 1, null);

CREATE INDEX index_company ON company USING btree (company_id);

