
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'TURKIYE', 'TURKEY');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'ABHAZYA', 'ABKHAZIA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'AFGANISTAN', 'AFGHANISTAN');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'ALMANYA', 'GERMANY');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'AMERIKA BIRLESIK DEVLETLERI', 'UNITED STATES');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'ANDORRA', 'ANDORRA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'ANGOLA', 'ANGOLA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'ANTIGUA VE BARBUDA','ANTIGUA AND BARBUDA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'ARJANTIN', 'ARGENTINA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'ARNAVUTLUK', 'ALBANIA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'AVUSTRALYA', 'AUSTRALIA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'AVUSTURYA', 'AUSTRIA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'AZERBAYCAN', 'AZERBAIJAN');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'BAHAMALAR', 'BAHAMAS');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'BAHREYN', 'BAHRAIN');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'BANGLADEŞ', 'BANGLADESH');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'BARBADOS', 'BARBADOS');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'BATI SAHRA', 'WESTERN SAHARA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'BELCIKA','BELGIUM');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'BELIZE', 'BELIZE');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'BENIN', 'BENIN');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'BEYAZ RUSYA', 'REPUBLIC OF BELARUS');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'BUTAN KRALLIGI', 'KINGDOM OF BHUTAN');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'BIRLESIK ARAP EMIRLIKLERI', 'UNITED ARAB EMIRATES');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'BOLIVYA', 'BOLIVIA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'BOSNA HERSEK', 'BOSNIA AND HERZEGOVINA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'BOTSVANA', 'BOTSWANA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'BREZILYA', 'BRAZIL');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'BRUNEI', 'BRUNEI');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'BULGARISTAN', 'BULGARIA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'BURKINA FASO', 'BURKINA FASO');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'BURUNDI', 'BURUNDI');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'CEZAYIR', 'ALGERIA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'CIBUTI', 'DJIBOUTI');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'CAD', 'CHAD');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'CEK CUMHURIYETI', 'CZECH REPUBLIC');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'CIN HALK CUMHURIYETI', 'PEOPLES REPUBLIC OF CHINA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'DAGLIK KARABAG CUMHURIYETI', 'NAGORNO-KARABAKH REPUBLIC ');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'DANIMARKA', 'DENMARK');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'DOGU TIMOR', 'EAST TIMOR');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'DOMINIK CUMHURIYETI', 'DOMINICAN REPUBLIC');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'DOMINIKA', 'DOMINICA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'EKVADOR', 'ECUADOR');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'EKVATOR GINESI', 'EQUATORIAL GUINEA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'EL SALVADOR', 'EL SALVADOR');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'ENDONEZYA', 'INDONESIA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'ERITRE', 'ERITREA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'ERMENISTAN', 'ARMENIA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'ESTONYA', 'ESTONIA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'ETIYOPYA', 'ETHIOPIA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'FAS', 'MOROCCO');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'FIJI', 'FIJI');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'FILDISI SAHILLERI', 'IVORY COAST');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'FILIPINLER', 'PHILIPPINES');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'FILISTIN', 'PALESTINE');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'FINLANDIYA', 'FINLAND');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'FRANSA', 'FRANCE');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'GABON','GABON');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'GAMBIYA', 'GAMBIA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'GANA', 'GHANA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'GINE', 'GUINEA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'GINE BISSAU', 'GINE BISSAU');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'GRENADA', 'GRENADA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'GUYANA', 'GUYANA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'GUATEMALA', 'GUATEMALA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'GUNEY AFRIKA CUMHURIYETI', 'SOUTH AFRICA REPUBLIC');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'GUNEY KORE', 'SOUTH KOREA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'GUNEY OSETYA', 'SOUTH OSSETIA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'GUNEY SUDAN', 'SOUTH SUDAN');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'GURCISTAN', 'GEORGIA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'HAITI', 'HAITI');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'HIRVATISTAN', 'CROATIA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'HINDISTAN', 'INDIA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'HOLLANDA', 'NETHERLANDS');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'HONDURAS', 'HONDURAS');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'IRAK', 'IRAQ');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'INGILTERE', 'ENGLAND');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'IRAN', 'PERSIA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'IRLANDA', 'IRELAND');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'ISPANYA', 'SPAIN');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'ISRAIL', 'ISRAEL');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'ISVEC', 'SWEDEN');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'ISVICRE', 'SWITZERLAND');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'ITALYA', 'ITALY');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'IZLANDA', 'ICELAND');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'JAMAIKA', 'JAMAICA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'JAPONYA', 'JAPAN');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'KAMBOCYA', 'CAMBODIA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'KAMERUN', 'CAMEROON');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'KANADA', 'CANADA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'KARADAG', 'MONTENEGRO');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'KAZAKISTAN', 'KAZAKHISTAN');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'KENYA', 'KENYA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'KIRGIZISTAN', 'KYRGYZSTAN');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'KIBRIS CUMHURIYETI', 'CYPRUS');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'KIRIBATI', 'KIRIBATI');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'KOLOMBIYA', 'COLOMBIA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'KOMORLAR', 'COMOROS');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'KONGO', 'CONGO');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'KONGO DEMOKRATIK CUMHURIYETI', 'DEMOCRATIC REBUPLIC OF THE CONGO ');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'KOSOVA', 'KOSOVA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'KOSTA RIKA', 'COSTA RICA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'KUVEYT', 'KUWAIT');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'KUZEY KIBRIS TURK CUMHURIYETI', 'TURKISH REPUBLIC OF NORTHEN CYPRUS ');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'KUZEY KORE', 'NORTH KOREA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'KUBA', 'CUBA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'LAOS', 'LAOS');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'LESOTHO', 'LESOTHO');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'LETONYA', 'LATVIA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'LIBERYA', 'LIBERIA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'LIBYA', 'LIBYA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'LIECHTENSTEIN', 'LIECHTENSTEIN');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'LITVANYA', 'LITHUANIA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'LUBNAN', 'LEBANON');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'LUKSEMBURG', 'LUXEMBOURG');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'MISIR', 'EGYPT');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'MACARISTAN', 'HUNGARY');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'MADAGASKAR', 'MADAGASCAR');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'MAKEDONYA CUMHURIYETI', 'REBUPLIC OF MACEDONIA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'MALAVI', 'MALAWI');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'MALDIVLER', 'MALDIVES');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'MALEZYA', 'MALAYSIA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'MALI', 'MALI');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'MALTA', 'MALTA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'MARSHALL ADALARI', 'MARSHALL ISLANDS');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'MOLDOVA', 'MOLDOVA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'MOZAMBIK', 'MOZAMBIQUE');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'NAMIBYA', 'NAMIBIA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'NIKARAGUA', 'NICARAGUA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'NIJER', 'NIGER');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'NIJERYA', 'NIGERIA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'NORVEC', 'NORWAY');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'ORTA AFRIKA CUMHURIYETI', 'CENTRAL AFRICAN REPUBLIC');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'OZBEKISTAN', 'UZBEKISTAN');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'PAKISTAN', 'PAKISTAN');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'PALAU', 'PALAU');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'PANAMA', 'PANAMA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'PAPUA', 'PAPUA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'PARAGUAY', 'PARAGUAY');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'PERU', 'PERU');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'POLONYA', 'POLAND');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'PORTEKIZ', 'PORTUGAL');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'PORTO RIKO', 'PORTO RICO');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'ROMANYA', 'ROMANIA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'RUANDA', 'RWANDA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'RUSYA FEDERASYONU', 'RUSSIAN FEDERATION');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'SAINT KITTS', 'SAINT KITTS');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'SAINT LUCIA', 'SAINT LUCIA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'SAINT VINCENT ve GRENADINLER', 'SAINT VINCENT AND THE GRENADINES ');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'SAMOA', 'SAMOA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'SAN MARINO', 'SAN MARINO');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'SAO TOME ve PRINCIPE', 'SAO TOME AND PRINCIPE');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'SEALAND', 'SEALAND');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'SENEGAL', 'SENEGAL');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'SEYSELLER', 'SEYCHELLES');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'SIRBISTAN', 'SERBIA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'SIERRA LEONE', 'SIERRA LEONE');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'SINGAPUR', 'SINGAPORE');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'SLOVAKYA', 'SLOVAKIA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'SLOVENYA', 'SLOVENIA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'SOLOMON ADALARI', 'SOLOMON ISLANDS');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'SOMALI', 'SOMALIA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'SOMALILAND', 'SOMALILAND');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'SRI LANKA', 'SRI LANKA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'SUDAN', 'SUDAN');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'SURINAM', 'SURINAME');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'SURIYE', 'SYRIA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'SUUDI ARABISTAN', 'SAUDI ARABIA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'SVAZILAND', 'SWAZILAND');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'SILI', 'CHILE');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'TACIKISTAN', 'TAJIKISTAN');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'TANZANYA', 'TANZANIA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'TAYLAND', 'THAILAND');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'TAYVAN', 'TAIWAN');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'TOGO', 'TOGO');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'TONGA', 'TONGA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'TRANSDINYESTER', 'TRANSNISTRIA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'TRINAD ve TOBAGO', 'TRINAD AND TOBAGO ');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'TUNUS', 'TUNISIA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'TUVALU', 'TUVALU');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'TURKMENISTAN', 'TURKMENISTAN');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'UGANDA', 'UGANDA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'UKRAYNA', 'UKRAINE');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'UMMAN', 'OMAN');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'URUGAY', 'URUGUAY');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'URDUN', 'JORDAN');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'VANUATU', 'VANUATU');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'VATIKAN', 'VATICAN');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'VENEZUELA', 'VENEZUELAN');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'VIETNAM', 'VIETNAMASE');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'YEMEN', 'YEMEN');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'YENI ZELANDA', 'NEW ZELAND');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'YESIL BURUN', 'CAPE VERDE');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'YUNANISTAN', 'GREECE');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'ZAMBIYAV', 'ZAMBIA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'ZIMBABVE', 'ZIMBABWE');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'MEKSIKA', 'MEXICAN');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'NAURU', 'NAURU');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'NEPAL', 'NEPAL');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'MONAKO','MONACO');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'MORITANYA', 'MAURITANIA');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'MORITIUS', 'MAURITIUS');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'KATAR', 'QATAR');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'BURMA (MYANMAR)', 'MYANMAR');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'HONG KONG', 'HONG KONG');
INSERT INTO public.country (country_id, "name", "english_name") VALUES(nextval('sq_country'), 'MAKAO', 'MACAU');

INSERT INTO public.role (role_id, "role_name", "description_tr", "description_en") VALUES(nextval('sq_role'), 'SUPER_ADMIN', 'SÜPER ADMİN', 'SUPER ADMIN');
INSERT INTO public.role (role_id, "role_name", "description_tr", "description_en") VALUES(nextval('sq_role'), 'ADMIN', 'ADMİN', 'ADMIN');
INSERT INTO public.role (role_id, "role_name", "description_tr", "description_en") VALUES(nextval('sq_role'), 'MANAGER', 'MÜDÜR', 'MANAGER');
INSERT INTO public.role (role_id, "role_name", "description_tr", "description_en") VALUES(nextval('sq_role'), 'USER', 'KULLANICI', 'USER');
INSERT INTO public.role (role_id, "role_name", "description_tr", "description_en") VALUES(nextval('sq_role'), 'TECHNICAL_SUPPORT_SPECIALIST', 'TEKNİK DESTEK UZMANI', 'TECHNICAL SUPPORT SPECIALIST');



INSERT INTO public.front_route (front_route_id, "path", "key", "is_protected_route", "is_root", "is_leaf") VALUES(nextval('sq_front_route'), '/', 'default', true, true, false);
INSERT INTO public.front_route (front_route_id, "path", "key", "is_protected_route", "is_root", "is_leaf") VALUES(nextval('sq_front_route'), '/index', 'index', true, true, false);
INSERT INTO public.front_route (front_route_id, "path", "key", "is_protected_route", "is_root", "is_leaf") VALUES(nextval('sq_front_route'), '/search-company', 'searchCompany', true, true, false);
INSERT INTO public.front_route (front_route_id, "path", "key", "is_protected_route", "is_root", "is_leaf") VALUES(nextval('sq_front_route'), '/search-user', 'searchUser', true, true, false);
INSERT INTO public.front_route (front_route_id, "path", "key", "is_protected_route", "is_root", "is_leaf") VALUES(nextval('sq_front_route'), '/contact-page', 'contactPage', true, true, false);
INSERT INTO public.front_route (front_route_id, "path", "key", "is_protected_route", "is_root", "is_leaf") VALUES(nextval('sq_front_route'), '/info-page', 'infoPage', true, true, false);
INSERT INTO public.front_route (front_route_id, "path", "key", "is_protected_route", "is_root", "is_leaf") VALUES(nextval('sq_front_route'), '/get-all-users', 'getAllUsers', true, true, false);
INSERT INTO public.front_route (front_route_id, "path", "key", "is_protected_route", "is_root", "is_leaf") VALUES(nextval('sq_front_route'), '/save-users', 'saveUsers', true, true, false);
INSERT INTO public.front_route (front_route_id, "path", "key", "is_protected_route", "is_root", "is_leaf") VALUES(nextval('sq_front_route'), '/user-detail', 'userDetail', true, true, false);
INSERT INTO public.front_route (front_route_id, "path", "key", "is_protected_route", "is_root", "is_leaf") VALUES(nextval('sq_front_route'), '/user/:userid', 'userByUserId', true, true, false);
INSERT INTO public.front_route (front_route_id, "path", "key", "is_protected_route", "is_root", "is_leaf") VALUES(nextval('sq_front_route'), '/edit-user/:userid', 'editUserByUserId', true, true, false);
INSERT INTO public.front_route (front_route_id, "path", "key", "is_protected_route", "is_root", "is_leaf") VALUES(nextval('sq_front_route'), '/update-my-account-password', 'updateMyAccountPassword', true, true, false);
INSERT INTO public.front_route (front_route_id, "path", "key", "is_protected_route", "is_root", "is_leaf") VALUES(nextval('sq_front_route'), '/update-my-account/:username', 'updateMyAccountPasswordByUsername', true, true, false);
INSERT INTO public.front_route (front_route_id, "path", "key", "is_protected_route", "is_root", "is_leaf") VALUES(nextval('sq_front_route'), '*', 'every', true, true, false);
